Build Power App/Build Power App/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Build_Power_App.Controllers
{
    public class ProjectController : Controller
    {
        private BuildPowerEntities db = new BuildPowerEntities();
        // GET: Project
        public ActionResult Projects()
        {
            return View(db.Projects.ToList());
        }

        public ActionResult AddProject()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult AddProject(FormCollection form, HttpPostedFileBase file)
        {

            if (file == null)
            {
                ViewBag.mess = "Fill the Form....";
                return PartialView();


            }
            else
            {
                string path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);

                path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);

                Project yangi = new Project();
                yangi.ProjectName = Request.Form["projectname"];
                yangi.Description = Request.Form["description"];
                yangi.CompanyWebsite = Request.Form["website"];
                yangi.CompanyName = Request.Form["company"];
                yangi.Location = Request.Form["location"];
                yangi.Price = Request.Form["price"];
                yangi.Picture = "/Content/images/" + file.FileName;

                db.Projects.Add(yangi);
                db.SaveChanges();

                return RedirectToAction("Projects");

            }
        }


        public ActionResult EditProject(int id)
        {
            ViewBag.model = db.Projects.Find(id);
            
            
            return PartialView();
        }
        [HttpPost]
        public ActionResult EditProject(int id, FormCollection form, HttpPostedFileBase file)
        {
            Project yangi = db.Projects.Find(id);
            yangi.ProjectName = Request.Form["projectname"];
            yangi.Description = Request.Form["description"];
            yangi.CompanyWebsite = Request.Form["website"];
            yangi.CompanyName = Request.Form["company"];
            yangi.Location = Request.Form["location"];
            yangi.Price = Request.Form["price"];

            if (file != null)
            {
                string path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);                
                yangi.Picture = "/Content/images/" + file.FileName ;
            } 
            else
            {               
                yangi.Picture = yangi.Picture;
            }

            db.Entry(yangi).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Projects");            
        }
        public ActionResult DetailsProject(int id)
        {
            ViewBag.model = db.Projects.Find(id);
            if (ViewBag.model != null)
                return PartialView(ViewBag.model);
            return HttpNotFound();
        }

        public ActionResult DeleteProject(int id)
        {
            ViewBag.model = db.Projects.Find(id);
            if (ViewBag.model != null)
                return PartialView(ViewBag.model);
            return HttpNotFound();
          
        }
        [HttpPost]
        public ActionResult DeleteProject(int id,  FormCollection collection)
        {
            try
            {
                db.Projects.Remove(db.Projects.Find(id));
                db.SaveChanges();

                return RedirectToAction("Projects");
            }
            catch
            {
                return View();
            }
          
        }

    }
}

Build Power App/Build Power App/Views/Project/AddProject.cshtml
<div class="modal-content" style="width:900px;     position: absolute; left: -130px;">
    <div class="modal-header" style="border-bottom:0;    padding-top: 40px; margin-top:-15px;">
        <h3 style="right: 30px; top: 5px; position: absolute;"><button class="close" data-dismiss="modal" area-hidden="true" style="padding:0;"><i class="material-icons" style="font-size: 36px; color: red; border-color: red; background: antiquewhite; padding:0;">close</i></button></h3>

    </div>
    <div class="modal-body" style="padding: 10px;
    padding-top: 0px;">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-text card-header-success">
                    <div class="card-text">
                        <h4 class="card-title">Add Form</h4>
                        @if (ViewBag.mess != null)
                        {
                          <h4 class="card-title" style="color:red">@ViewBag.mess</h4>
                        }
                        
                    </div>
                </div>
                <div class="card-body" style="padding-top:15px">

                    <form action="/Project/AddProject" method="post" enctype = "multipart/form-data">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                    <label for="projectname">Project Name</label>
                                    <input type="text" class="form-control" name="projectname" id="projectname" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="company">Company Name</label>
                                <input type="text" class="form-control" name="company" id="company" required>
                            </div>
                                           
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="description">Description:</label>
                                <textarea class="form-control" rows="4" name="description" id="description" required></textarea>
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" name="price" id="price" required>
                            </div>
                            <div class="form-group col-md-8">
                                <label for="location">Location</label>
                                <input type="text" class="form-control" name="location" id="location" required>
                            </div>
                        </div>

                        <div class="form-row">
                            
                            <div class="form-group col-md-6">
                                <label for="website">Company Website</label>
                                <input type="text" class="form-control" name="website" id="website" required>
                            </div>
                        </div>


                    

                        <div class="form-row">
                            <label for="file">Project Image</label>
                         
                           <input id="file" type="file" name="file" class="form-control-file" onchange="show(this)" style="margin-bottom: 10px;">
                         
                            <div class="col-md-6"></div>
                            <div class="col-md-6">
                                <img id="user_img"
                                     height="160"
                                     width="210"
                                     style="border:solid 1px;
                                     position: absolute;
                                    bottom: -50px;
                                    right: 16px;
                                    width: 341px;
                                    height: 178px;
                                    object-fit: cover;" />

                                <script type="text/javascript">

                           function show(input) {
                               if (input.files && input.files[0]) {
                                   var filerdr = new FileReader();
                                   filerdr.onload = function (e) {
                                       $('#user_img').attr('src', e.target.result);
                                   }
                                   filerdr.readAsDataURL(input.files[0]);
                               }
                           }
                                </script>
                            </div>
                        </div>



                        <button type="submit" class="fadeIn fourth btn btn-success">Add</button>
                    </form>

                </div>
            </div>
        </div>



    </div>
</div>

Build Power App/Build Power App/Views/Project/DeleteProject.cshtml
@model Build_Power_App.Project

<div class="modal-content" style="width:900px;     position: absolute; left: -130px;">
    <div class="modal-header" style="border-bottom:0;    padding-top: 40px; margin-top:-15px;">
        <h3 style="right: 30px; top: 5px; position: absolute;"><button class="close" data-dismiss="modal" area-hidden="true" style="padding:0;"><i class="material-icons" style="font-size: 36px; color: red; border-color: red; background: antiquewhite; padding:0;">close</i></button></h3>

    </div>
    <div class="modal-body" style="padding: 10px;
    padding-top: 0px;">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-text card-header-danger">
                    <div class="card-text">
                        <h5 class="card-title">Are you sure you want to delete this?</h5>
                    </div>
                </div>
                <div class="card-body" style="padding-top:15px">

                    <div>
                     
                        <div class="form-row">
                            <div class="form-group col-md-6">

                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.ProjectName)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.ProjectName)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Location)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Location)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Price)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Price)
                                    </dd>
                                                                    
                                    <dt>
                                        @Html.DisplayNameFor(model => model.CompanyName)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.CompanyName)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.CompanyWebsite)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.CompanyWebsite)
                                    </dd>

                                </dl>
                            </div>
                            <div class="form-group col-md-6">

                                <dl class="dl-horizontal">
                               

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Description)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Picture)
                                    </dt>

                                    <dd>

                                        <img src="@Url.Content("~/Content/images/" + System.IO.Path.GetFileName(Model.Picture))" style="width:400px; height:250px;  object-fit: contain;" alt="" />
                                    </dd>

                           

                                </dl>
                            </div>
                        </div>


                    


                        <form action="/Project/DeleteProject" method="post" style="margin-top: -80px;">
                            <input type="hidden" class="fadeIn fourth btn btn-danger" name="id" value="@ViewBag.model.ID">
                            <input type="submit" class="fadeIn fourth btn btn-danger" value="Delete">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel </button>
                        </form>

                    </div>
                </div>
            </div>



        </div>
    </div>

</div>

Build Power App/Build Power App/Views/Project/DetailsProject.cshtml
@model Build_Power_App.Project

<div class="modal-content" style="width:900px; position: absolute; left: -130px;  overflow-y: auto;">
    <div class="modal-header" style="border-bottom:0;    padding-top: 40px; margin-top:-15px;">
        <h3 style="right: 30px; top: 5px; position: absolute;"><button class="close" data-dismiss="modal" area-hidden="true" style="padding:0;"><i class="material-icons" style="font-size: 36px; color: red; border-color: red; background: antiquewhite; padding:0;">close</i></button></h3>

    </div>
    <div class="modal-body" style="padding: 10px;
    padding-top: 0px;   overflow-y: auto !important;">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-text card-header-success">
                    <div class="card-text">
                        <h5 class="card-title">Detail Form </h5>
                    </div>
                </div>
                <div class="card-body" style="padding-top:15px">

                    <div>

                        <div class="form-row">
                            <div class="form-group col-md-6">

                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.ProjectName)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.ProjectName)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Location)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Location)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Price)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Price)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.CompanyName)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.CompanyName)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.CompanyWebsite)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.CompanyWebsite)
                                    </dd>

                                </dl>
                            </div>
                            <div class="form-group col-md-6">

                                <dl class="dl-horizontal">


                                    <dt>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Description)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Picture)
                                    </dt>

                                    <dd>

                                        <img src="@Url.Content("~/Content/images/" + System.IO.Path.GetFileName(Model.Picture))" style="width:400px; height:250px;  object-fit: contain;" alt="" />
                                    </dd>



                                </dl>
                            </div>
                        </div>





                        <form  style="margin-top: -80px;">
                            <input type="hidden" class="fadeIn fourth btn btn-success" name="id" value="@ViewBag.model.ID">
                            <input type="submit" class="fadeIn fourth btn btn-success" data-dismiss="modal" area-hidden="true" id="show_first" value="Close">
                         
                        </form>

                    </div>
                </div>
            </div>

           
        </div>
    </div>

</div>

Build Power App/Build Power App/Views/Project/EditProject.cshtml
<div class="modal-content" style="width:900px;     position: absolute; left: -130px;">
    <div class="modal-header" style="border-bottom:0;    padding-top: 40px; margin-top:-15px;">
        <h3 style="right: 30px; top: 5px; position: absolute;"><button class="close" data-dismiss="modal" area-hidden="true" style="padding:0;"><i class="material-icons" style="font-size: 36px; color: red; border-color: red; background: antiquewhite; padding:0;">close</i></button></h3>

    </div>
    <div class="modal-body" style="padding: 10px;
    padding-top: 0px;">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-text card-header-success">
                    <div class="card-text">
                        <h4 class="card-title">Edit Form</h4>
                        @if (ViewBag.mess != null)
                        {
                            <h4 class="card-title" style="color:red">@ViewBag.mess</h4>
                        }

                    </div>
                </div>
                <div class="card-body" style="padding-top:15px">

                    <form action="/Project/EditProject" method="post" enctype="multipart/form-data">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="projectname">Project Name</label>
                                <input type="text" class="form-control" name="projectname" id="projectname" value="@ViewBag.model.ProjectName" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="company">Company Name</label>
                                <input type="text" class="form-control" name="company" id="company" value="@ViewBag.model.CompanyName" required>
                            </div>

                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="description">Description:</label>
                                <textarea class="form-control" rows="4" name="description" id="description" required>@ViewBag.model.Description</textarea>
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" name="price" id="price"value="@ViewBag.model.Price"  required>
                            </div>
                            <div class="form-group col-md-8">
                                <label for="location">Location</label>
                                <input type="text" class="form-control" name="location" id="location" value="@ViewBag.model.Location" required>
                            </div>
                        </div>


                        <div class="form-row">

                            <div class="form-group col-md-6">
                            </div>
                            <div class="form-row col-md-6" style="margin-left: 5px; margin-top: 15px;">
                                <label for="file">New Image</label>
                                <input id="file" type="file" name="file" class="form-control-file" onchange="show(this)" style="margin-bottom: 10px;">
                            </div>
                        </div>


                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <label for="website">Old Image</label>
                                <img src="@Url.Content("~/Content/images/" + System.IO.Path.GetFileName(@ViewBag.model.Picture))" style="width:400px; height:250px;  object-fit: contain;" alt="" />
                            </div>
                            <div class="form-group col-md-6">
                                <label for="website">New Image</label>
                                <img id="user_img" style="border: solid 3px aqua;
                                     position: absolute;
                                     margin-top: 42px;
                                     right: 10px;
                                     width: 381px;
                                     height: 224px;
                                     object-fit: cover;" />

                                <script type="text/javascript">

                           function show(input) {
                               if (input.files && input.files[0]) {
                                   var filerdr = new FileReader();
                                   filerdr.onload = function (e) {
                                       $('#user_img').attr('src', e.target.result);
                                   }
                                   filerdr.readAsDataURL(input.files[0]);
                               }
                           }
                                </script>
                            </div>
                        </div>


                     
                        <input type="hidden" class="fadeIn fourth btn btn-danger" name="id" value="@ViewBag.model.ID">
                        <button type="submit" class="fadeIn fourth btn btn-success">Update</button>
                    </form>

                </div>
            </div>
        </div>



    </div>
</div>

Build Power App/Build Power App/Views/Project/Projects.cshtml
@model IEnumerable<Build_Power_App.Project>


<style>

</style>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog" role="dialog"></div>
</div>



<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="card-header card-header-success">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="card-title">List of Projects</h3>
                </div>
                <div class="col-md-6" style="text-align:right">
                    <a href="@Url.Action("AddProject", "Project")" class="compItem btn btn-info btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">add</i> </a>
                </div>
            </div>


        </div>
        <div class="card-body table-responsive">
            <table class="table table-hover" id="CustomerGrid">
                <thead class="text-success">
                    <tr>
                        <th>ID</th>
                        <th>Picture</th>
                        <th>ProjectName</th>
                        <th>Location</th>
                        <th>Price</th>
                        <th>Description</th>                      
                        <th>CompanyName</th>
                        <th>CompanyWebsite</th>
                        
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ID</td>
                            <td>
                                <img src="@item.Picture" style="width:130px; height:130px;  object-fit: cover;" alt="Alternate Text" />


                            </td>
                            <td>@item.ProjectName</td>
                            <td>@item.Location</td>
                          
                            <td>@item.Price</td>
                            <td>@item.Description</td>
                            <td>@item.CompanyName</td>
                            <td>@item.CompanyWebsite</td>
                           

                            @*<td>@Html.ActionLink(item.OrganizationName, "Details",
                                new { id = item.ID }, new { @class = "compItem" })</td>*@
                            <td>
                                <a href="@Url.Action("DetailsProject", "Project",new { id = item.ID})" class="compItem btn btn-info btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">subject</i> </a>
                                <a href="@Url.Action("EditProject", "Project",new { id = item.ID})" class="compItem btn btn-success btn-just-icon btn-fill btn-round btn-wd" style="color: white;"><i class="material-icons">mode_edit</i> </a>
                                <a href="@Url.Action("DeleteProject", "Project",new { id = item.ID})" class="compItem btn btn-danger btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">delete</i> </a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @section scripts
{
                <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
                </script>
            }
        </div>
    </div>
</div>