Build Power App/Build Power App/Controllers/MessagesController.cs
using Build_Power_App.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Build_Power_App.Controllers
{
    public class MessagesController : Controller
    {
        // GET: Messages

      private  BuildPowerEntities db = new BuildPowerEntities();
        public ActionResult List()
        {
            ViewBag.messages = db.Messages;
            return View();
        }

   
        public ActionResult Answer(int id)
        {
            ViewBag.model = db.Messages.Find(id);
            Control.IDMessage = id;

            if (ViewBag.model != null)
                return PartialView();
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Answer(FormCollection form)
        {
            Message kimga = db.Messages.FirstOrDefault(x=>x.ID== Control.IDMessage);
            string title = form["title"];
            string description = form["description"];


            var fromAddress = new MailAddress("dnetseniordeveloper@gmail.com", "Construction Admin");
            var toAddress = new MailAddress(kimga.Email, kimga.Name);
            const string fromPassword = "Web@1234";
             string subject = title;
             string body = description;

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
            };
            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body
            })
            {
                smtp.Send(message);
            }



            return RedirectToAction("List", "Messages");
        }

    }
}

Build Power App/Build Power App/Controllers/NewController.cs
using Build_Power_App.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Build_Power_App.Controllers
{
    public class NewController : Controller
    {

        private BuildPowerEntities db = new BuildPowerEntities();

        // GET: News
        public ActionResult News()
        {
            ViewBag.categories = db.Categories.ToList();
            ViewBag.authors = db.UserRoles.ToList();
            return View(db.News);
        }

        public ActionResult EditNews(int id)
        {
            ViewBag.model = db.News.Find(id);

            ViewBag.categories = db.Categories;

            return PartialView();
        }

        [HttpPost]
        public ActionResult EditNews(int id, FormCollection form, HttpPostedFileBase file)
        {
            News yangi = db.News.Find(id);
            yangi.Title = Request.Form["Title"];
            yangi.Description = Request.Form["description"];
            yangi.DateTime = DateTime.Now;
            yangi.CategoryID = int.Parse(Request.Form["category"]);
           

            if (file != null)
            {
                string path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                yangi.Picture = "/Content/images/" + file.FileName;
            }
            else
            {
                yangi.Picture = yangi.Picture;
            }

            db.Entry(yangi).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("News");
        }

        public ActionResult DetailsNews(int id)
        {
            ViewBag.model = db.News.Find(id);
            ViewBag.categories = db.Categories;
            ViewBag.roles = db.UserRoles;
            ViewBag.users = db.Users;

            if (ViewBag.model != null)
                return PartialView(ViewBag.model);
            return HttpNotFound();
        }

        public ActionResult DeleteNews(int id)
        {
            ViewBag.model = db.News.Find(id);
            ViewBag.categories = db.Categories;
            ViewBag.roles = db.UserRoles;
            ViewBag.users = db.Users;
            if (ViewBag.model != null)
                return PartialView(ViewBag.model);
            return HttpNotFound();

        }
        [HttpPost]
        public ActionResult DeleteNews(int id, FormCollection collection)
        {
            try
            {
                db.News.Remove(db.News.Find(id));
                db.SaveChanges();

                return RedirectToAction("News");
            }
            catch
            {
                return View();
            }

        }

        public ActionResult AddNews()
        {
            ViewBag.categories = db.Categories;
            return PartialView();
        }

        [HttpPost]
        public ActionResult AddNews(FormCollection form, HttpPostedFileBase file)
        {

            if (file == null)
            {
                ViewBag.mess = "Fill the Form....";
                return PartialView();
            }
            else
            {
                string path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);

                path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(file.FileName));
                file.SaveAs(path);

                News yangi = new News();
                yangi.Title = Request.Form["Title"];
                yangi.Description = Request.Form["description"];
                yangi.CategoryID = int.Parse(Request.Form["author"]);
                yangi.DateTime = DateTime.Now;
                yangi.AuthorID = Status.UserID;

               
                yangi.Picture = "/Content/images/" + file.FileName;

                db.News.Add(yangi);
                db.SaveChanges();

                return RedirectToAction("News");

            }
        }
    }
}

Build Power App/Build Power App/Views/Messages/Answer.cshtml
<div class="modal-content" style="width:900px;     position: absolute; left: -130px;">
    <div class="modal-header" style="border-bottom:0;    padding-top: 40px; margin-top:-15px;">
        <h3 style="right: 30px; top: 5px; position: absolute;"><button class="close" data-dismiss="modal" area-hidden="true" style="padding:0;"><i class="material-icons" style="font-size: 36px; color: red; border-color: red; background: antiquewhite; padding:0;">close</i></button></h3>

    </div>
    <div class="modal-body" style="padding: 10px;
    padding-top: 0px;">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-text card-header-success">
                    <div class="card-text">
                        <h4 class="card-title">Answer Form</h4>
                        @if (ViewBag.mess != null)
                        {
                            <h4 class="card-title" style="color:red">@ViewBag.mess</h4>
                        }

                    </div>
                </div>
                <div class="card-body" style="padding-top:15px">

                    <form action="/Messages/answer" method="post" enctype="multipart/form-data">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Title">Title</label>
                                <input type="text" class="form-control" name="title" id="Title" required>
                            </div>


                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="description">Description:</label>
                                <textarea class="form-control" rows="4" name="description" id="description" required></textarea>
                            </div>
                        </div>
               

                      


                        <button type="submit" class="fadeIn fourth btn btn-success">Send to Gmail</button>
                    </form>

                </div>
            </div>
        </div>



    </div>
</div>

Build Power App/Build Power App/Views/Messages/List.cshtml
<style>

</style>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog" role="dialog"></div>
</div>



<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="card-header card-header-success">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="card-title">List of Messages</h3>
                </div>
                @*<div class="col-md-6" style="text-align:right">
                    <a href="@Url.Action("AddNews", "New")" class="compItem btn btn-info btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">add</i> </a>
                </div>*@
            </div>


        </div>
        <div class="card-body table-responsive">
            <table class="table table-hover" id="CustomerGrid">
                <thead class="text-success">
                    <tr>
                        <th>ID</th>
                        <th>From</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Subject</th>
                        <th>Message</th>
                       


                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.messages)
                    {
                        <tr>
                            <td>@item.ID</td>
                           
                            <td>@item.Name</td>
                            <td>@item.Email</td>

                            <td>@item.Phone</td>
                            <td>@item.Subject</td>
                            <td>@item.Description</td>


                            @*<td>@Html.ActionLink(item.OrganizationName, "Details",
                                new { id = item.ID }, new { @class = "compItem" })</td>*@
                            <td>
                                <a href="@Url.Action("Answer", "Messages",new { id = item.ID})" class="compItem btn btn-info btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">comment</i> </a>
                                @*<a href="@Url.Action("EditNews", "New",new { id = item.ID})" class="compItem btn btn-success btn-just-icon btn-fill btn-round btn-wd" style="color: white;"><i class="material-icons">mode_edit</i> </a>
                                <a href="@Url.Action("DeleteNews", "New",new { id = item.ID})" class="compItem btn btn-danger btn-just-icon btn-fill btn-round" style="color: white;"><i class="material-icons">delete</i> </a>*@

                            </td>
                        </tr>
                                    }
                </tbody>
            </table>
            @section scripts
{
                <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
                </script>
            }
        </div>
    </div>
</div>